
client_config:
  session: ${oc.env:SESSION}
  api_id: ${oc.env:API_ID}
  api_hash: ${oc.env:API_HASH}
  phone: ${oc.env:PHONE}

database:
  user: ${oc.env:POSTGRES_USER}
  passw: ${oc.env:POSTGRES_PASS}
  host: ${oc.env:POSTGRES_HOST}
  port: ${oc.env:POSTGRES_PORT,5432}
  db_url: postgresql+psycopg2://${.user}:${.passw}@${.host}:${.port}/${.user}
